services:
  kafka1: 
    image: apache/kafka:latest
    networks:
      - kafka-cluster
    container_name: kafka1

    environment: 
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=1

      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller

      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_LISTENERS=CLIENT://:29092,CONTROLLER://:9094,EXTERNAL://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka1:29092,EXTERNAL://localhost:9092
      
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka1:9094,2@kafka2:9094,3@kafka3:9094
    ports: 
      - 9091:9092
      
  kafka2: 
    image: apache/kafka:latest
    networks:
      - kafka-cluster
    container_name: kafka2
    environment: 
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=1

      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=broker,controller

      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_LISTENERS=CLIENT://:29092,CONTROLLER://:9094,EXTERNAL://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka2:29092,EXTERNAL://localhost:9092
      
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka1:9094,2@kafka2:9094,3@kafka3:9094
    ports: 
      - 9092:9092
      
  kafka3: 
    image: apache/kafka:latest
    networks:
      - kafka-cluster
    container_name: kafka3

    environment: 
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=1

      - KAFKA_NODE_ID=3
      - KAFKA_PROCESS_ROLES=broker,controller

      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_LISTENERS=CLIENT://:29092,CONTROLLER://:9094,EXTERNAL://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka3:29092,EXTERNAL://localhost:9092
      
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka1:9094,2@kafka2:9094,3@kafka3:9094  
    ports: 
      - 9093:9092
      
  kafdrop: 
    image: obsidiandynamics/kafdrop:latest
    networks:
      - kafka-cluster
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports: 
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka1:29092,kafka2:29092,kafka3:29092
volumes:
  kafka_data:
    driver: local
networks:
  kafka-cluster:
    driver: bridge